#!/usr/bin/env python3
"""
MC Bot Summoner
===============
A self-contained Flask web app that summons any number of FAKE Minecraft
players (offline-mode / "cracked" bots) to a target server.

Inspired by the mindcraft project (https://github.com/mindcraft-bots/mindcraft)
which uses the Node.js `mineflayer` library. This app wraps that approach in a
friendly web UI and orchestrates many bot processes from Python.

On first run it automatically:
  * checks that Node.js + npm are installed
  * writes a `bot_runner.js` Mineflayer script into ./runtime
  * runs `npm install mineflayer` into ./runtime/node_modules

Then it starts a Flask server on http://0.0.0.0:3000.

Usage:
    python3 app.py

Requirements:
    - Python 3.8+  (Flask is pip-installed automatically if missing)
    - Node.js 16+  (must be installed already)
    - npm          (ships with Node.js)

The target server MUST be running in offline mode (server.properties:
`online-mode=false`) for offline players to join.
"""

import os
import sys
import json
import subprocess
import threading
import time
import uuid
import queue
import random
import shutil
import collections
import re
import signal
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths & runtime config
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent.resolve()
RUNTIME_DIR = BASE_DIR / "runtime"
BOT_RUNNER_PATH = RUNTIME_DIR / "bot_runner.js"

NODE_BIN = shutil.which("node")
NPM_BIN = shutil.which("npm")

PORT = int(os.environ.get("PORT", 3000))
SPAWN_DELAY = 0.35  # seconds between spawning consecutive bots (anti-flood)

# ---------------------------------------------------------------------------
# Make sure Flask is installed (bootstrap). We try to import, and if it's
# missing we pip-install it on the fly so the app is truly "just run app.py".
# ---------------------------------------------------------------------------
try:
    import flask
    from flask import Flask, request, jsonify, Response
except ImportError:
    print("[bootstrap] Flask not found, installing via pip ...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "flask"])
    import flask  # noqa: F401
    from flask import Flask, request, jsonify, Response  # noqa: E402

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Global state
# ---------------------------------------------------------------------------
bots_lock = threading.Lock()
bots = {}  # bot_id -> dict(name, host, port, version, behavior, reconnect, status, started_at, pid, proc)

log_buffer = collections.deque(maxlen=400)  # recent log entries (ring buffer)
sub_lock = threading.Lock()
log_subscribers = []  # list of queue.Queue for SSE clients

spawn_queue = queue.Queue()

READY = False
INSTALL_ERROR = None

# ---------------------------------------------------------------------------
# The Node.js bot runner (Mineflayer, offline mode)
# Written into ./runtime/bot_runner.js at startup.
# ---------------------------------------------------------------------------
BOT_RUNNER_JS = r'''/* Auto-generated by app.py. Mineflayer offline-mode bot runner. */
const mineflayer = require('mineflayer');

const args = process.argv.slice(2);
// args: name host port version behavior reconnect
const config = {
  name: args[0] || 'Bot',
  host: args[1] || 'localhost',
  port: parseInt(args[2] || '25565', 10),
  version: (args[3] && args[3] !== 'auto') ? args[3] : null,
  behavior: args[4] || 'idle',
  reconnect: String(args[5] || 'true') === 'true',
};

let bot = null;
let behaviorTimer = null;
let reconnectTimer = null;
let shouldRun = true;

function emit(obj) {
  try { process.stdout.write(JSON.stringify(obj) + '\n'); } catch (e) {}
}
function log(msg) { emit({ type: 'log', message: String(msg), time: Date.now() }); }
function setStatus(s) { emit({ type: 'status', status: s, time: Date.now() }); }

function startBehavior(b) {
  if (behaviorTimer) { clearInterval(behaviorTimer); behaviorTimer = null; }
  try {
    switch (config.behavior) {
      case 'idle':
        behaviorTimer = setInterval(() => {
          try { b.look(Math.random() * Math.PI * 2, (Math.random() - 0.5) * 0.6); } catch (e) {}
        }, 4000 + Math.random() * 4000);
        break;
      case 'wander':
        behaviorTimer = setInterval(() => {
          try {
            const r = Math.random();
            if (r < 0.25) {
              b.setControlState('jump', true);
              setTimeout(() => { try { b.setControlState('jump', false); } catch (e) {} }, 400);
            } else {
              b.look(Math.random() * Math.PI * 2, 0);
              b.setControlState('forward', true);
              setTimeout(() => { try { b.setControlState('forward', false); } catch (e) {} }, 1000 + Math.random() * 2500);
            }
          } catch (e) {}
        }, 2400);
        break;
      case 'jump':
        behaviorTimer = setInterval(() => {
          try { b.setControlState('jump', true); setTimeout(() => { try { b.setControlState('jump', false); } catch (e) {} }, 300); } catch (e) {}
        }, 1400 + Math.random() * 1400);
        break;
      case 'spin':
        let yaw = 0;
        behaviorTimer = setInterval(() => {
          try { yaw += 0.45; b.look(yaw % (Math.PI * 2), 0); } catch (e) {}
        }, 90);
        break;
      case 'sneak':
        behaviorTimer = setInterval(() => {
          try {
            const sneak = Math.random() > 0.5;
            b.setControlState('sneak', sneak);
          } catch (e) {}
        }, 3000);
        break;
      case 'follow':
        behaviorTimer = setInterval(() => {
          try {
            const players = Object.values(b.players || {}).filter(p => p && p.entity && p.username !== b.username);
            if (players.length) {
              const target = players[0].entity.position;
              b.lookAt(target.offset(0, 1.6, 0));
              const dist = b.entity.position.distanceTo(target);
              b.setControlState('forward', dist > 2.5);
              b.setControlState('sprint', dist > 8);
            } else {
              b.setControlState('forward', false);
              b.setControlState('sprint', false);
            }
          } catch (e) {}
        }, 500);
        break;
      case 'chat':
        const msgs = ['hi', 'lol', 'gg', 'anyone here?', 'nice', 'brb', 'hello!', 'wow', 'cool', 'yo'];
        behaviorTimer = setInterval(() => {
          try { b.chat(msgs[Math.floor(Math.random() * msgs.length)]); } catch (e) {}
        }, 9000 + Math.random() * 7000);
        break;
      case 'punch':
        behaviorTimer = setInterval(() => {
          try {
            const target = b.nearestEntity(e => e && e.position && e.position.distanceTo(b.entity.position) < 4);
            if (target) {
              b.lookAt(target.position.offset(0, 1, 0));
              b.attack(target);
            }
          } catch (e) {}
        }, 2000);
        break;
      default: // idle
        behaviorTimer = setInterval(() => {
          try { b.look(Math.random() * Math.PI * 2, 0); } catch (e) {}
        }, 5000);
    }
  } catch (e) {
    log('behavior error: ' + (e && e.message));
  }
}

function createBot() {
  if (!shouldRun) return;
  setStatus('connecting');
  log('Connecting to ' + config.host + ':' + config.port + ' as "' + config.name + '"' + (config.version ? ' (v' + config.version + ')' : ' (auto version)'));

  const opts = {
    username: config.name,
    host: config.host,
    port: config.port,
    auth: 'offline',
    hideErrors: false,
  };
  if (config.version) opts.version = config.version;

  try {
    bot = mineflayer.createBot(opts);
  } catch (e) {
    log('createBot error: ' + (e && e.message));
    setStatus('error');
    if (shouldRun && config.reconnect) {
      reconnectTimer = setTimeout(createBot, 6000);
    }
    return;
  }

  bot.on('spawn', () => {
    setStatus('online');
    try {
      const p = bot.entity.position;
      log('Spawned at ' + p.x.toFixed(1) + ', ' + p.y.toFixed(1) + ', ' + p.z.toFixed(1) + ' (health ' + (bot.health != null ? bot.health.toFixed(0) : '?') + ')');
    } catch (e) { log('Spawned.'); }
    startBehavior(bot);
  });

  bot.on('health', () => {
    try { emit({ type: 'health', health: bot.health, food: bot.food, time: Date.now() }); } catch (e) {}
  });

  bot.on('chat', (username, message) => {
    if (username === config.name) return;
    log('[chat] ' + username + ': ' + message);
  });

  bot.on('kicked', (reason) => {
    let r = reason;
    try { if (typeof reason === 'object') r = JSON.stringify(reason); } catch (e) {}
    log('Kicked: ' + r);
    setStatus('offline');
  });

  bot.on('error', (err) => {
    log('Error: ' + (err && err.message ? err.message : err));
    setStatus('error');
  });

  bot.on('end', () => {
    if (behaviorTimer) { clearInterval(behaviorTimer); behaviorTimer = null; }
    setStatus('offline');
    log('Disconnected.');
    if (shouldRun && config.reconnect) {
      log('Reconnecting in 6s ...');
      reconnectTimer = setTimeout(createBot, 6000);
    }
  });
}

createBot();

function shutdown() {
  shouldRun = false;
  if (reconnectTimer) clearTimeout(reconnectTimer);
  if (behaviorTimer) clearInterval(behaviorTimer);
  try { bot && bot.quit('Bye'); } catch (e) {}
  setTimeout(() => process.exit(0), 400);
}
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
'''


# ---------------------------------------------------------------------------
# Environment bootstrap
# ---------------------------------------------------------------------------
def ensure_environment():
    """Check Node/npm, write bot_runner.js, install mineflayer if missing."""
    global READY, INSTALL_ERROR

    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)

    if not NODE_BIN:
        INSTALL_ERROR = ("Node.js was not found on your PATH. "
                         "Install Node.js 16+ from https://nodejs.org and restart.")
        print("[setup] ERROR: " + INSTALL_ERROR)
        return

    # Always (re)write the runner so it stays in sync with this app version.
    try:
        BOT_RUNNER_PATH.write_text(BOT_RUNNER_JS, encoding="utf-8")
    except Exception as e:
        INSTALL_ERROR = "Could not write bot_runner.js: " + str(e)
        print("[setup] ERROR: " + INSTALL_ERROR)
        return

    # Write a LOCAL package.json so npm installs into ./runtime/node_modules
    # instead of walking up and polluting a parent project.
    pkg_json = {
        "name": "mc-summoner-runtime",
        "version": "1.0.0",
        "private": True,
        "description": "Runtime deps for MC Bot Summoner bots (mineflayer).",
        "dependencies": {"mineflayer": "^4.20.1"},
    }
    try:
        (RUNTIME_DIR / "package.json").write_text(
            json.dumps(pkg_json, indent=2), encoding="utf-8")
    except Exception as e:
        INSTALL_ERROR = "Could not write package.json: " + str(e)
        print("[setup] ERROR: " + INSTALL_ERROR)
        return

    nm_mineflayer = RUNTIME_DIR / "node_modules" / "mineflayer"
    if not nm_mineflayer.exists():
        print("[setup] Installing mineflayer (one-time, ~30s) ...")
        try:
            subprocess.run(
                [NPM_BIN or "npm", "install",
                 "--no-audit", "--no-fund", "--loglevel=error"],
                cwd=str(RUNTIME_DIR),
                check=True,
                timeout=240,
            )
            print("[setup] mineflayer installed.")
        except subprocess.CalledProcessError as e:
            INSTALL_ERROR = ("npm install mineflayer failed (exit code %s). "
                             "Check your internet connection and npm setup."
                             % getattr(e, "returncode", "?"))
            print("[setup] ERROR: " + INSTALL_ERROR)
            return
        except subprocess.TimeoutExpired:
            INSTALL_ERROR = "npm install mineflayer timed out. Check your connection."
            print("[setup] ERROR: " + INSTALL_ERROR)
            return

    READY = True
    print("[setup] Ready. Node: %s | mineflayer present." % NODE_BIN)


# ---------------------------------------------------------------------------
# Name generation
# ---------------------------------------------------------------------------
NAME_ADJ = ["Cool", "Fast", "Brave", "Sly", "Mega", "Super", "Dark", "Epic",
            "Lucky", "Quick", "Iron", "Gold", "Red", "Cyber", "Neon", "Hyper",
            "Silent", "Wild", "Mighty", "Proto"]
NAME_NOUN = ["Steve", "Alex", "Creeper", "Zombie", "Miner", "Builder", "Knight",
             "Wizard", "Ninja", "Pirate", "Hunter", "Wolf", "Tiger", "Dragon",
             "Phoenix", "Gamer", "Pro", "Noob", "King", "Queen"]

NAME_RE = re.compile(r"^[A-Za-z0-9_]{3,16}$")


def sanitize_name(name):
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    name = name[:16]
    if len(name) < 3:
        name = (name + "Bot")[:16]
    return name


def generate_names(mode, prefix, count, existing):
    names = []
    used = set(existing)
    prefix = sanitize_name(prefix) if prefix else "Bot"

    def take(n):
        n = sanitize_name(n)
        base = n
        i = 1
        while n in used:
            suffix = "_" + str(i)
            n = (base[:16 - len(suffix)] + suffix)
            i += 1
        used.add(n)
        return n

    if mode == "prefix":
        for i in range(1, count + 1):
            s = str(i)
            base = prefix[:16 - len(s) - 1]
            names.append(take(base + "_" + s))
    elif mode == "steve":
        for i in range(count):
            names.append(take("Steve" + (str(i + 1) if i > 0 else "")))
    elif mode == "random":
        for _ in range(count):
            n = random.choice(NAME_ADJ) + random.choice(NAME_NOUN) + str(random.randint(1, 99))
            names.append(take(n[:16]))
    else:
        for i in range(count):
            names.append(take(prefix + "_" + str(i + 1)))
    return names


# ---------------------------------------------------------------------------
# Bot process management
# ---------------------------------------------------------------------------
def push_log(bot_id, name, message, kind="log"):
    entry = {
        "bot_id": bot_id,
        "name": name,
        "message": message,
        "kind": kind,  # log | status | error | system
        "time": int(time.time() * 1000),
    }
    log_buffer.append(entry)
    with sub_lock:
        dead = []
        for q in log_subscribers:
            try:
                q.put_nowait(entry)
            except Exception:
                dead.append(q)
        if dead:
            for q in dead:
                try:
                    log_subscribers.remove(q)
                except ValueError:
                    pass


def queue_bot(name, host, port, version, behavior, reconnect):
    bot_id = uuid.uuid4().hex[:10]
    info = {
        "id": bot_id,
        "name": name,
        "host": host,
        "port": port,
        "version": version,
        "behavior": behavior,
        "reconnect": reconnect,
        "status": "queued",
        "started_at": time.time(),
        "pid": None,
        "position": None,
        "health": None,
    }
    with bots_lock:
        bots[bot_id] = info
    spawn_queue.put({"bot_id": bot_id, "name": name, "host": host, "port": port,
                     "version": version, "behavior": behavior, "reconnect": reconnect})
    return bot_id


def do_spawn(job):
    bot_id = job["bot_id"]
    with bots_lock:
        info = bots.get(bot_id)
        if not info:
            return
        info["status"] = "connecting"
    cmd = [
        NODE_BIN,
        str(BOT_RUNNER_PATH),
        job["name"],
        job["host"],
        str(job["port"]),
        job["version"],
        job["behavior"],
        "true" if job["reconnect"] else "false",
    ]
    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=str(RUNTIME_DIR),
            text=True,
            bufsize=1,
            env=dict(os.environ, DEBUG=""),
        )
    except Exception as e:
        with bots_lock:
            if bot_id in bots:
                bots[bot_id]["status"] = "error"
        push_log(bot_id, job["name"], "Failed to launch: " + str(e), "error")
        return

    with bots_lock:
        if bot_id in bots:
            bots[bot_id]["pid"] = proc.pid
            bots[bot_id]["proc"] = proc
    threading.Thread(target=reader_thread, args=(bot_id, proc), daemon=True).start()


def spawn_worker():
    while True:
        job = spawn_queue.get()
        try:
            do_spawn(job)
        except Exception as e:
            print("[worker] spawn error:", e)
        time.sleep(SPAWN_DELAY)
        spawn_queue.task_done()


def reader_thread(bot_id, proc):
    name = ""
    with bots_lock:
        name = bots.get(bot_id, {}).get("name", "")
    try:
        for line in proc.stdout:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            try:
                obj = json.loads(line)
            except ValueError:
                push_log(bot_id, name, line, "log")
                continue
            t = obj.get("type")
            if t == "status":
                with bots_lock:
                    if bot_id in bots:
                        bots[bot_id]["status"] = obj.get("status", "offline")
                push_log(bot_id, name, "status -> " + obj.get("status", ""), "status")
            elif t == "log":
                push_log(bot_id, name, obj.get("message", ""), "log")
            elif t == "health":
                with bots_lock:
                    if bot_id in bots:
                        bots[bot_id]["health"] = obj.get("health")
            else:
                push_log(bot_id, name, json.dumps(obj), "log")
    except Exception as e:
        push_log(bot_id, name, "reader error: " + str(e), "error")
    finally:
        proc.wait()
        with bots_lock:
            if bot_id in bots:
                cur = bots[bot_id]["status"]
                if cur not in ("stopped", "error"):
                    bots[bot_id]["status"] = "offline"
        push_log(bot_id, name, "process exited (code %s)" % proc.returncode, "system")


def stop_bot(bot_id):
    with bots_lock:
        info = bots.get(bot_id)
        if not info:
            return False
        proc = info.get("proc")
        info["status"] = "stopped"
    if proc and proc.poll() is None:
        try:
            proc.terminate()
        except Exception:
            pass
        # hard kill after grace
        threading.Thread(target=lambda: (time.sleep(3),
                                         proc.poll() is None and (proc.kill() if proc.poll() is None else None)),
                         daemon=True).start()
    push_log(bot_id, info.get("name", ""), "Stopped by user.", "system")
    return True


def public_bot(info):
    return {
        "id": info["id"],
        "name": info["name"],
        "host": info["host"],
        "port": info["port"],
        "version": info["version"],
        "behavior": info["behavior"],
        "reconnect": info["reconnect"],
        "status": info["status"],
        "started_at": info["started_at"],
        "pid": info.get("pid"),
        "health": info.get("health"),
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.route("/")
def index():
    return HTML_PAGE


@app.route("/api/state")
def api_state():
    with bots_lock:
        blist = [public_bot(b) for b in bots.values()]
    counts = {"total": len(blist), "online": 0, "connecting": 0,
              "queued": 0, "offline": 0, "error": 0, "stopped": 0}
    for b in blist:
        s = b["status"]
        if s in counts:
            counts[s] += 1
        else:
            counts["offline"] += 1
    queued_pending = spawn_queue.qsize()
    return jsonify({
        "ready": READY,
        "install_error": INSTALL_ERROR,
        "node": NODE_BIN,
        "spawn_queue": queued_pending,
        "counts": counts,
        "bots": blist,
    })


@app.route("/api/spawn", methods=["POST"])
def api_spawn():
    if not READY:
        return jsonify({"error": INSTALL_ERROR or "Runtime not ready."}), 503
    data = request.get_json(silent=True) or {}

    host = (data.get("host") or "").strip()
    if not host:
        return jsonify({"error": "Server host/IP is required."}), 400
    try:
        port = int(data.get("port") or 25565)
    except ValueError:
        return jsonify({"error": "Port must be a number."}), 400
    if not (1 <= port <= 65535):
        return jsonify({"error": "Port must be between 1 and 65535."}), 400

    version = (data.get("version") or "auto").strip()
    behavior = (data.get("behavior") or "idle").strip()
    reconnect = bool(data.get("reconnect", True))
    name_mode = (data.get("name_mode") or "prefix").strip()
    prefix = (data.get("prefix") or "Bot").strip()
    try:
        count = int(data.get("count") or 1)
    except ValueError:
        return jsonify({"error": "Count must be a number."}), 400
    if count < 1:
        return jsonify({"error": "Count must be at least 1."}), 400
    if count > 100000:
        return jsonify({"error": "Count capped at 100000 for sanity. Each bot is a Node process (~40MB RAM)."}), 400

    with bots_lock:
        existing = [b["name"] for b in bots.values()]
    names = generate_names(name_mode, prefix, count, existing)

    ids = []
    for nm in names:
        bid = queue_bot(nm, host, port, version, behavior, reconnect)
        ids.append({"id": bid, "name": nm})

    push_log(None, "system",
             "Queued %d bot(s) -> %s:%s (%s)" % (len(names), host, port, behavior), "system")
    return jsonify({"queued": len(names), "bots": ids})


@app.route("/api/stop/<bot_id>", methods=["POST"])
def api_stop_one(bot_id):
    ok = stop_bot(bot_id)
    return jsonify({"ok": ok})


@app.route("/api/stop_all", methods=["POST"])
def api_stop_all():
    with bots_lock:
        ids = [bid for bid, b in bots.items() if b["status"] not in ("stopped", "offline", "error")]
    n = 0
    for bid in ids:
        if stop_bot(bid):
            n += 1
    push_log(None, "system", "Stopping %d active bot(s) ..." % n, "system")
    return jsonify({"stopping": n})


@app.route("/api/clear", methods=["POST"])
def api_clear():
    """Remove stopped/offline/error bots from the list."""
    with bots_lock:
        keep = {}
        removed = 0
        for bid, b in bots.items():
            if b["status"] in ("stopped", "offline", "error"):
                removed += 1
            else:
                keep[bid] = b
        bots.clear()
        bots.update(keep)
    return jsonify({"removed": removed})


@app.route("/api/logs")
def api_logs():
    """Server-Sent Events stream of live logs."""
    q = queue.Queue()
    with sub_lock:
        log_subscribers.append(q)

    def stream():
        # send recent history first
        yield "retry: 3000\n\n"
        for entry in list(log_buffer):
            yield "data: " + json.dumps(entry) + "\n\n"
        try:
            while True:
                try:
                    msg = q.get(timeout=20)
                    yield "data: " + json.dumps(msg) + "\n\n"
                except queue.Empty:
                    yield ": keepalive\n\n"
        finally:
            with sub_lock:
                if q in log_subscribers:
                    log_subscribers.remove(q)

    return Response(stream(), mimetype="text/event-stream", headers={
        "Cache-Control": "no-cache",
        "X-Accel-Buffering": "no",
        "Connection": "keep-alive",
    })


@app.route("/api/version_info")
def api_version_info():
    versions = [
        ("auto", "Auto-detect (ping server)"),
        ("1.21.4", "1.21.4"),
        ("1.21.1", "1.21.1"),
        ("1.20.6", "1.20.6"),
        ("1.20.4", "1.20.4"),
        ("1.20.1", "1.20.1"),
        ("1.19.4", "1.19.4"),
        ("1.19.2", "1.19.2"),
        ("1.18.2", "1.18.2"),
        ("1.17.1", "1.17.1"),
        ("1.16.5", "1.16.5"),
        ("1.12.2", "1.12.2"),
        ("1.8.9", "1.8.9"),
    ]
    behaviors = [
        ("idle", "Idle (look around)"),
        ("wander", "Wander (walk randomly)"),
        ("jump", "Jump repeatedly"),
        ("spin", "Spin in place"),
        ("sneak", "Toggle sneak"),
        ("follow", "Follow nearest player"),
        ("chat", "Chat random messages"),
        ("punch", "Punch nearby entities"),
    ]
    return jsonify({"versions": versions, "behaviors": behaviors})


# ---------------------------------------------------------------------------
# HTML / CSS / JS (single-page UI)
# ---------------------------------------------------------------------------
HTML_PAGE = r'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>MC Bot Summoner</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root {
    --bg: #0f1115;
    --bg-2: #15181f;
    --panel: #1b1f29;
    --panel-2: #21262f;
    --border: #2c333d;
    --border-2: #3a4250;
    --text: #e6e9ef;
    --muted: #8b94a3;
    --muted-2: #6b7280;
    --grass: #5cb85c;
    --grass-2: #4ade80;
    --emerald: #10b981;
    --emerald-d: #059669;
    --gold: #f5b042;
    --danger: #ef4444;
    --warn: #f59e0b;
    --info: #38bdf8;
    --purple: #a78bfa;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    background: var(--bg);
    color: var(--text);
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    background-image:
      radial-gradient(circle at 15% -10%, rgba(92,184,92,0.08), transparent 40%),
      radial-gradient(circle at 90% 0%, rgba(16,185,129,0.06), transparent 35%);
  }
  .pixel { font-family: 'Press Start 2P', monospace; letter-spacing: 0.5px; }

  header.topbar {
    position: sticky; top: 0; z-index: 30;
    backdrop-filter: blur(8px);
    background: rgba(15,17,21,0.85);
    border-bottom: 1px solid var(--border);
    padding: 14px 20px;
    display: flex; align-items: center; gap: 16px; flex-wrap: wrap;
  }
  .logo {
    display: flex; align-items: center; gap: 12px;
  }
  .logo-icon {
    width: 40px; height: 40px; border-radius: 8px;
    background: linear-gradient(135deg, #4a8a3a 0 50%, #6b5a3a 50% 100%);
    border: 2px solid #2c2c2c;
    box-shadow: inset 0 0 0 2px rgba(0,0,0,0.25), 0 2px 8px rgba(0,0,0,0.4);
    position: relative; flex-shrink: 0;
  }
  .logo-icon::after {
    content: ''; position: absolute; inset: 6px;
    background:
      linear-gradient(#3a3a3a, #3a3a3a) 30% 30% / 14% 14% no-repeat,
      linear-gradient(#3a3a3a, #3a3a3a) 60% 30% / 14% 14% no-repeat,
      linear-gradient(#3a3a3a, #3a3a3a) 45% 55% / 30% 14% no-repeat;
    opacity: 0.55;
  }
  .logo h1 {
    margin: 0; font-size: 14px; color: var(--grass-2);
    font-family: 'Press Start 2P', monospace;
  }
  .logo p { margin: 4px 0 0; font-size: 11px; color: var(--muted); }

  .stats { display: flex; gap: 8px; flex-wrap: wrap; margin-left: auto; }
  .stat {
    background: var(--panel); border: 1px solid var(--border);
    border-radius: 10px; padding: 7px 12px; min-width: 76px;
    display: flex; flex-direction: column; align-items: center;
  }
  .stat .n { font-size: 18px; font-weight: 700; font-family: 'JetBrains Mono', monospace; }
  .stat .l { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.6px; }
  .stat.online .n { color: var(--grass-2); }
  .stat.connecting .n { color: var(--warn); }
  .stat.queued .n { color: var(--info); }
  .stat.offline .n { color: var(--muted); }
  .stat.total .n { color: var(--text); }

  main {
    flex: 1; width: 100%; max-width: 1320px; margin: 0 auto;
    padding: 20px; display: grid; gap: 18px;
    grid-template-columns: 340px 1fr;
    align-items: start;
  }
  @media (max-width: 900px) { main { grid-template-columns: 1fr; } }

  .card {
    background: var(--panel); border: 1px solid var(--border);
    border-radius: 14px; overflow: hidden;
  }
  .card-h {
    padding: 13px 16px; border-bottom: 1px solid var(--border);
    display: flex; align-items: center; gap: 10px;
    background: linear-gradient(180deg, rgba(255,255,255,0.02), transparent);
  }
  .card-h h2 { margin: 0; font-size: 13px; font-weight: 600; letter-spacing: 0.3px; }
  .card-h .dot { width: 9px; height: 9px; border-radius: 50%; }
  .card-b { padding: 16px; }

  .field { margin-bottom: 14px; }
  .field:last-child { margin-bottom: 0; }
  .field label {
    display: block; font-size: 11px; color: var(--muted);
    text-transform: uppercase; letter-spacing: 0.6px; margin-bottom: 6px; font-weight: 600;
  }
  .row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  input[type=text], input[type=number], select {
    width: 100%; background: var(--bg-2); border: 1px solid var(--border-2);
    color: var(--text); padding: 9px 11px; border-radius: 9px;
    font-size: 13px; font-family: inherit; outline: none;
    transition: border-color .15s, box-shadow .15s;
  }
  input:focus, select:focus { border-color: var(--emerald); box-shadow: 0 0 0 3px rgba(16,185,129,0.15); }
  select { appearance: none; cursor: pointer;
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%238b94a3' stroke-width='2'><polyline points='6 9 12 15 18 9'/></svg>");
    background-repeat: no-repeat; background-position: right 11px center; padding-right: 30px;
  }
  .hint { font-size: 11px; color: var(--muted-2); margin-top: 5px; }

  .check { display: flex; align-items: center; gap: 9px; cursor: pointer; user-select: none; font-size: 13px; }
  .check input { appearance: none; width: 18px; height: 18px; border: 1px solid var(--border-2);
    border-radius: 5px; background: var(--bg-2); cursor: pointer; position: relative; flex-shrink: 0; }
  .check input:checked { background: var(--emerald); border-color: var(--emerald); }
  .check input:checked::after { content: ''; position: absolute; left: 5px; top: 1px; width: 5px; height: 10px;
    border: solid white; border-width: 0 2px 2px 0; transform: rotate(45deg); }

  .btn {
    border: none; border-radius: 10px; padding: 11px 16px; font-size: 13px;
    font-weight: 600; cursor: pointer; transition: transform .08s, filter .15s, background .15s;
    display: inline-flex; align-items: center; justify-content: center; gap: 8px;
    font-family: inherit;
  }
  .btn:active { transform: translateY(1px); }
  .btn-primary { background: linear-gradient(180deg, var(--grass-2), var(--emerald-d)); color: #06281c; }
  .btn-primary:hover { filter: brightness(1.08); }
  .btn-danger { background: linear-gradient(180deg, #f87171, #dc2626); color: #fff; }
  .btn-danger:hover { filter: brightness(1.08); }
  .btn-ghost { background: var(--panel-2); color: var(--text); border: 1px solid var(--border-2); }
  .btn-ghost:hover { background: var(--border); }
  .btn-sm { padding: 6px 10px; font-size: 11px; border-radius: 8px; }
  .btn:disabled { opacity: 0.5; cursor: not-allowed; }
  .btn-row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }

  .right-col { display: grid; gap: 18px; min-width: 0; }

  .bots-grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 10px;
    max-height: 56vh; overflow-y: auto; padding: 4px;
  }
  .bots-grid::-webkit-scrollbar, .console::-webkit-scrollbar { width: 9px; }
  .bots-grid::-webkit-scrollbar-thumb, .console::-webkit-scrollbar-thumb {
    background: var(--border-2); border-radius: 6px;
  }
  .bots-grid::-webkit-scrollbar-track, .console::-webkit-scrollbar-track { background: transparent; }

  .bot-card {
    background: var(--panel-2); border: 1px solid var(--border); border-radius: 12px;
    padding: 11px; display: flex; align-items: center; gap: 11px; position: relative;
    transition: border-color .15s, transform .08s;
  }
  .bot-card:hover { border-color: var(--border-2); }
  .bot-card.active { border-color: var(--emerald); box-shadow: 0 0 0 2px rgba(16,185,129,0.15); }
  .avatar {
    width: 38px; height: 38px; border-radius: 8px; position: relative; flex-shrink: 0;
    overflow: hidden; display: flex; align-items: center; justify-content: center;
    border: 1px solid rgba(0,0,0,0.3); box-shadow: inset 0 0 0 1px rgba(255,255,255,0.05);
  }
  .avatar .letter { font-weight: 700; font-size: 16px; color: #fff; text-shadow: 0 1px 2px rgba(0,0,0,0.5); }
  .avatar img { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }
  .bot-info { flex: 1; min-width: 0; }
  .bot-name { font-size: 13px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .bot-meta { font-size: 10px; color: var(--muted); margin-top: 2px; display: flex; gap: 6px; align-items: center; }
  .badge { font-size: 10px; font-weight: 600; padding: 2px 7px; border-radius: 99px; text-transform: uppercase; letter-spacing: 0.4px; }
  .b-online { background: rgba(74,222,128,0.15); color: var(--grass-2); }
  .b-connecting { background: rgba(245,158,11,0.15); color: var(--warn); }
  .b-queued { background: rgba(56,189,248,0.15); color: var(--info); }
  .b-offline { background: rgba(139,148,163,0.15); color: var(--muted); }
  .b-error { background: rgba(239,68,68,0.15); color: var(--danger); }
  .b-stopped { background: rgba(139,148,163,0.12); color: var(--muted-2); }
  .stop-x {
    position: absolute; top: 6px; right: 6px; width: 20px; height: 20px; border-radius: 6px;
    background: rgba(239,68,68,0.12); color: var(--danger); border: none; cursor: pointer;
    display: none; align-items: center; justify-content: center; font-size: 14px; line-height: 1;
  }
  .bot-card:hover .stop-x { display: flex; }

  .empty {
    grid-column: 1 / -1; text-align: center; padding: 40px 20px; color: var(--muted-2);
  }
  .empty .big { font-size: 32px; margin-bottom: 8px; opacity: 0.5; }

  .console {
    background: #0a0c10; border: 1px solid var(--border); border-radius: 10px;
    padding: 12px; font-family: 'JetBrains Mono', monospace; font-size: 12px; line-height: 1.55;
    height: 240px; overflow-y: auto; color: #c8d0db;
  }
  .console .line { white-space: pre-wrap; word-break: break-word; }
  .console .ts { color: #5b6472; margin-right: 8px; }
  .console .tag { display: inline-block; min-width: 70px; color: var(--info); margin-right: 8px; }
  .console .k-status { color: var(--warn); }
  .console .k-error { color: var(--danger); }
  .console .k-system { color: var(--purple); }
  .console .k-log { color: #c8d0db; }

  .console-tools { display: flex; gap: 8px; align-items: center; }
  .console-tools .filter-on { color: var(--info); font-size: 11px; }

  .banner {
    margin: 0 0 14px; padding: 11px 14px; border-radius: 10px; font-size: 12.5px;
    border: 1px solid var(--warn); background: rgba(245,158,11,0.1); color: var(--warn);
    display: flex; gap: 10px; align-items: flex-start;
  }
  .banner.err { border-color: var(--danger); background: rgba(239,68,68,0.1); color: var(--danger); }
  .banner.ok { border-color: var(--emerald); background: rgba(16,185,129,0.1); color: var(--grass-2); }

  .count-pill {
    display: inline-flex; align-items: center; gap: 6px; background: var(--bg-2);
    border: 1px solid var(--border-2); border-radius: 99px; padding: 4px 10px; font-size: 11px;
    color: var(--muted);
  }
  .count-pill b { color: var(--text); }

  .seg { display: flex; gap: 4px; background: var(--bg-2); border: 1px solid var(--border-2); border-radius: 9px; padding: 3px; }
  .seg button { flex: 1; border: none; background: transparent; color: var(--muted); padding: 7px 6px;
    font-size: 11px; font-weight: 600; border-radius: 7px; cursor: pointer; font-family: inherit; }
  .seg button.on { background: var(--panel-2); color: var(--text); }

  footer {
    margin-top: auto; border-top: 1px solid var(--border); background: var(--bg-2);
    padding: 14px 20px; text-align: center; font-size: 11px; color: var(--muted-2);
  }
  footer a { color: var(--muted); text-decoration: none; }
  footer a:hover { color: var(--grass-2); }

  .toast-wrap { position: fixed; bottom: 20px; right: 20px; z-index: 50; display: flex; flex-direction: column; gap: 8px; }
  .toast { background: var(--panel); border: 1px solid var(--border-2); border-left: 3px solid var(--emerald);
    color: var(--text); padding: 11px 15px; border-radius: 10px; font-size: 12.5px; min-width: 220px;
    box-shadow: 0 8px 24px rgba(0,0,0,0.4); animation: slideIn .25s ease; }
  .toast.err { border-left-color: var(--danger); }
  @keyframes slideIn { from { transform: translateX(20px); opacity: 0; } to { transform: none; opacity: 1; } }

  .spinner { width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.25); border-top-color: #fff;
    border-radius: 50%; animation: spin 0.7s linear infinite; display: inline-block; }
  @keyframes spin { to { transform: rotate(360deg); } }
  .pulse { animation: pulse 1.3s ease-in-out infinite; }
  @keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.45; } }
</style>
</head>
<body>
  <header class="topbar">
    <div class="logo">
      <div class="logo-icon" aria-hidden="true"></div>
      <div>
        <h1>MC BOT SUMMONER</h1>
        <p>Offline-mode fake players &middot; powered by Mineflayer</p>
      </div>
    </div>
    <div class="stats" id="stats">
      <div class="stat total"><span class="n" id="c-total">0</span><span class="l">Total</span></div>
      <div class="stat online"><span class="n" id="c-online">0</span><span class="l">Online</span></div>
      <div class="stat connecting"><span class="n" id="c-connecting">0</span><span class="l">Connecting</span></div>
      <div class="stat queued"><span class="n" id="c-queued">0</span><span class="l">Queued</span></div>
      <div class="stat offline"><span class="n" id="c-offline">0</span><span class="l">Offline</span></div>
    </div>
  </header>

  <main>
    <!-- LEFT: config -->
    <section class="card" style="position: sticky; top: 92px;">
      <div class="card-h"><span class="dot" style="background:var(--grass-2)"></span><h2>Summon Config</h2></div>
      <div class="card-b">
        <div id="banner-area"></div>

        <div class="field">
          <label for="host">Server Host / IP</label>
          <input type="text" id="host" placeholder="play.example.net" value="localhost" />
        </div>
        <div class="row">
          <div class="field">
            <label for="port">Port</label>
            <input type="number" id="port" value="25565" min="1" max="65535" />
          </div>
          <div class="field">
            <label for="version">Version</label>
            <select id="version"></select>
          </div>
        </div>

        <div style="height:1px;background:var(--border);margin:14px 0;"></div>

        <div class="field">
          <label>Player Naming</label>
          <div class="seg" id="name-mode">
            <button data-v="prefix" class="on">Prefix</button>
            <button data-v="steve">Steve#</button>
            <button data-v="random">Random</button>
          </div>
        </div>
        <div class="field" id="prefix-field">
          <label for="prefix">Name Prefix</label>
          <input type="text" id="prefix" value="Bot" maxlength="14" />
          <div class="hint">Names become Prefix_1, Prefix_2 ... (max 16 chars)</div>
        </div>
        <div class="row">
          <div class="field">
            <label for="count">How many players?</label>
            <input type="number" id="count" value="5" min="1" max="100000" />
            <div class="hint">Each bot is a Node process (~40MB RAM). They spawn ~3/sec to avoid flooding.</div>
          </div>
          <div class="field">
            <label for="behavior">Behavior</label>
            <select id="behavior"></select>
          </div>
        </div>
        <div class="field">
          <label class="check"><input type="checkbox" id="reconnect" checked /> Auto-reconnect when dropped</label>
        </div>

        <div class="btn-row" style="margin-top:4px;">
          <button class="btn btn-primary" id="summon-btn">Summon</button>
          <button class="btn btn-danger" id="stop-all-btn">Stop All</button>
        </div>
        <button class="btn btn-ghost btn-sm" id="clear-btn" style="width:100%;margin-top:10px;">Clear stopped / offline</button>
      </div>
    </section>

    <!-- RIGHT: bots + logs -->
    <div class="right-col">
      <section class="card">
        <div class="card-h">
          <span class="dot" style="background:var(--info)"></span>
          <h2>Active Players</h2>
          <span class="count-pill" id="queue-pill" style="margin-left:auto;">Queue: <b id="qsize">0</b></span>
          <span class="count-pill"><b id="bot-count">0</b> summoned</span>
        </div>
        <div class="card-b">
          <div class="bots-grid" id="bots-grid">
            <div class="empty">
              <div class="big">&#9881;</div>
              <div>No players summoned yet.</div>
              <div style="margin-top:6px;font-size:11px;">Configure a server on the left and hit <b>Summon</b>.</div>
            </div>
          </div>
        </div>
      </section>

      <section class="card">
        <div class="card-h">
          <span class="dot" style="background:var(--purple)"></span>
          <h2>Live Console</h2>
          <span class="filter-on" id="filter-tag" style="margin-left:auto;display:none;">filter: <b id="filter-name"></b> <a href="#" id="filter-clear" style="color:var(--info)">(clear)</a></span>
          <div class="console-tools">
            <button class="btn btn-ghost btn-sm" id="autoscroll-btn">Auto-scroll: ON</button>
            <button class="btn btn-ghost btn-sm" id="clear-log-btn">Clear</button>
          </div>
        </div>
        <div class="card-b">
          <div class="console" id="console"></div>
        </div>
      </section>
    </div>
  </main>

  <footer>
    MC Bot Summoner &mdash; offline-mode bots via <a href="https://github.com/PrismarineJS/mineflayer" target="_blank" rel="noopener">mineflayer</a>,
    inspired by <a href="https://github.com/mindcraft-bots/mindcraft" target="_blank" rel="noopener">mindcraft</a>.
    &nbsp;|&nbsp; Target server must run with <code>online-mode=false</code>.
  </footer>

  <div class="toast-wrap" id="toasts"></div>

<script>
const $ = (s) => document.querySelector(s);
const VERSIONS = [
  ["auto","Auto-detect (ping server)"],
  ["1.21.4","1.21.4"],["1.21.1","1.21.1"],["1.20.6","1.20.6"],["1.20.4","1.20.4"],
  ["1.20.1","1.20.1"],["1.19.4","1.19.4"],["1.19.2","1.19.2"],["1.18.2","1.18.2"],
  ["1.17.1","1.17.1"],["1.16.5","1.16.5"],["1.12.2","1.12.2"],["1.8.9","1.8.9"]
];
const BEHAVIORS = [
  ["idle","Idle (look around)"],["wander","Wander (walk randomly)"],["jump","Jump repeatedly"],
  ["spin","Spin in place"],["sneak","Toggle sneak"],["follow","Follow nearest player"],
  ["chat","Chat random messages"],["punch","Punch nearby entities"]
];

// populate selects
(function(){
  const v = $('#version'), b = $('#behavior');
  VERSIONS.forEach(([k,l])=>{ const o=document.createElement('option'); o.value=k; o.textContent=l; v.appendChild(o); });
  BEHAVIORS.forEach(([k,l])=>{ const o=document.createElement('option'); o.value=k; o.textContent=l; b.appendChild(o); });
})();

// name mode segmented control
let nameMode = 'prefix';
document.querySelectorAll('#name-mode button').forEach(btn=>{
  btn.addEventListener('click', ()=>{
    document.querySelectorAll('#name-mode button').forEach(b=>b.classList.remove('on'));
    btn.classList.add('on');
    nameMode = btn.dataset.v;
    $('#prefix-field').style.display = (nameMode === 'prefix') ? '' : 'none';
  });
});

// state
let botsCache = [];
let filterBotId = null;
let autoscroll = true;

function toast(msg, kind){
  const t = document.createElement('div');
  t.className = 'toast' + (kind==='err'?' err':'');
  t.textContent = msg;
  $('#toasts').appendChild(t);
  setTimeout(()=>{ t.style.opacity='0'; t.style.transition='opacity .3s'; setTimeout(()=>t.remove(),300); }, 3200);
}

function nameColor(name){
  let h = 0;
  for (let i=0;i<name.length;i++) h = name.charCodeAt(i) + ((h<<5)-h);
  const hue = Math.abs(h) % 360;
  return `hsl(${hue}, 45%, 38%)`;
}
function initial(name){ return (name||'?').charAt(0).toUpperCase(); }
function fmtUptime(sec){
  if (sec < 60) return Math.floor(sec)+'s';
  if (sec < 3600) return Math.floor(sec/60)+'m';
  return Math.floor(sec/3600)+'h '+(Math.floor(sec/60)%60)+'m';
}
function badgeClass(s){ return 'b-'+s; }

function renderBots(bots){
  const grid = $('#bots-grid');
  $('#bot-count').textContent = bots.length;
  if (!bots.length){
    grid.innerHTML = `<div class="empty"><div class="big">&#9881;</div><div>No players summoned yet.</div><div style="margin-top:6px;font-size:11px;">Configure a server on the left and hit <b>Summon</b>.</div></div>`;
    return;
  }
  // sort: online first, then connecting, queued, then offline/stopped
  const order = {online:0,connecting:1,queued:2,error:3,offline:4,stopped:5};
  bots.sort((a,b)=> (order[a.status]??9) - (order[b.status]??9) || a.name.localeCompare(b.name));
  grid.innerHTML = bots.map(b=>{
    const av = `<div class="avatar" style="background:${nameColor(b.name)}"><span class="letter">${initial(b.name)}</span><img src="https://mc-heads.net/avatar/${encodeURIComponent(b.name)}/48" onerror="this.remove()" alt=""></div>`;
    const uptime = (b.status==='online'||b.status==='connecting') ? fmtUptime((Date.now()/1000)-b.started_at) : b.behavior;
    return `<div class="bot-card ${filterBotId===b.id?'active':''}" data-id="${b.id}">
      <button class="stop-x" data-stop="${b.id}" title="Stop">&times;</button>
      ${av}
      <div class="bot-info">
        <div class="bot-name" title="${b.name}">${b.name}</div>
        <div class="bot-meta">
          <span class="badge ${badgeClass(b.status)}">${b.status}</span>
          <span>${uptime}</span>
        </div>
      </div>
    </div>`;
  }).join('');
  // bind click -> filter
  grid.querySelectorAll('.bot-card').forEach(card=>{
    card.addEventListener('click', (e)=>{
      if (e.target.dataset.stop) return;
      const id = card.dataset.id;
      if (filterBotId === id){ filterBotId = null; } else { filterBotId = id; }
      updateFilterUI(); renderBots(botsCache);
    });
  });
  grid.querySelectorAll('[data-stop]').forEach(btn=>{
    btn.addEventListener('click', (e)=>{ e.stopPropagation(); stopOne(btn.dataset.stop); });
  });
}

function updateFilterUI(){
  const ft = $('#filter-tag');
  if (filterBotId){
    const b = botsCache.find(x=>x.id===filterBotId);
    ft.style.display=''; $('#filter-name').textContent = b?b.name:filterBotId;
  } else { ft.style.display='none'; }
}

function renderStats(counts, qsize){
  $('#c-total').textContent = counts.total;
  $('#c-online').textContent = counts.online;
  $('#c-connecting').textContent = counts.connecting;
  $('#c-queued').textContent = counts.queued;
  $('#c-offline').textContent = counts.offline + counts.stopped + counts.error;
  $('#qsize').textContent = qsize;
  const pill = $('#queue-pill');
  pill.style.display = qsize > 0 ? '' : 'none';
}

function renderBanner(ready, err){
  const area = $('#banner-area');
  if (err){
    area.innerHTML = `<div class="banner err"><b>&#9888; Setup issue:</b><div>${err}</div></div>`;
    $('#summon-btn').disabled = true;
  } else if (!ready){
    area.innerHTML = `<div class="banner"><span class="spinner"></span><div>Preparing runtime &mdash; installing Mineflayer assets ...</div></div>`;
    $('#summon-btn').disabled = true;
  } else {
    area.innerHTML = `<div class="banner ok">&#10003; Runtime ready &mdash; Mineflayer installed. Summon away.</div>`;
    $('#summon-btn').disabled = false;
  }
}

// ---- API calls ----
async function fetchState(){
  try {
    const r = await fetch('/api/state');
    const d = await r.json();
    botsCache = d.bots;
    renderBots(d.bots);
    renderStats(d.counts, d.spawn_queue||0);
    renderBanner(d.ready, d.install_error);
  } catch(e){ console.warn(e); }
}
async function summon(){
  const body = {
    host: $('#host').value.trim(),
    port: parseInt($('#port').value||'25565',10),
    version: $('#version').value,
    behavior: $('#behavior').value,
    count: parseInt($('#count').value||'1',10),
    name_mode: nameMode,
    prefix: $('#prefix').value.trim() || 'Bot',
    reconnect: $('#reconnect').checked,
  };
  if (!body.host){ toast('Enter a server host/IP.', 'err'); return; }
  if (body.count > 50){ toast('Heads up: ' + body.count + ' bots will use ~' + Math.round(body.count*0.04) + 'MB RAM. Spawning gradually...', 'err'); }
  const btn = $('#summon-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span> Summoning';
  try {
    const r = await fetch('/api/spawn', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body)});
    const d = await r.json();
    if (!r.ok){ toast(d.error||'Spawn failed', 'err'); }
    else { toast(`Summoning ${d.queued} player(s) ...`); }
  } catch(e){ toast('Network error: '+e.message, 'err'); }
  finally { btn.disabled = false; btn.innerHTML = 'Summon'; fetchState(); }
}
async function stopOne(id){
  await fetch('/api/stop/'+id, {method:'POST'});
  toast('Stopping '+ (botsCache.find(b=>b.id===id)?.name || id));
  fetchState();
}
async function stopAll(){
  const btn = $('#stop-all-btn');
  btn.disabled = true; btn.innerHTML = '<span class="spinner"></span> Stopping';
  await fetch('/api/stop_all', {method:'POST'});
  toast('Stopping all bots ...');
  btn.disabled = false; btn.innerHTML = 'Stop All';
  fetchState();
}
async function clearStopped(){
  const r = await fetch('/api/clear', {method:'POST'});
  const d = await r.json();
  toast(`Cleared ${d.removed} bot(s).`);
  fetchState();
}

// ---- SSE logs ----
function connectLogs(){
  const es = new EventSource('/api/logs');
  es.onmessage = (ev)=>{
    try { addLog(JSON.parse(ev.data)); } catch(e){}
  };
  es.onerror = ()=>{ es.close(); setTimeout(connectLogs, 2500); };
}
function addLog(entry){
  if (filterBotId && entry.bot_id && entry.bot_id !== filterBotId) return;
  const con = $('#console');
  const ts = new Date(entry.time);
  const tstr = ts.toLocaleTimeString('en-US',{hour12:false}) + '.' + String(ts.getMilliseconds()).padStart(3,'0').slice(0,2);
  const tag = entry.name && entry.name !== 'system' ? entry.name : 'system';
  const line = document.createElement('div');
  line.className = 'line';
  line.innerHTML = `<span class="ts">${tstr}</span><span class="tag">${escapeHtml(tag)}</span><span class="k-${entry.kind||'log'}">${escapeHtml(entry.message)}</span>`;
  con.appendChild(line);
  // cap lines
  while (con.childNodes.length > 600) con.removeChild(con.firstChild);
  if (autoscroll) con.scrollTop = con.scrollHeight;
}
function escapeHtml(s){ return String(s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }

// ---- wiring ----
$('#summon-btn').addEventListener('click', summon);
$('#stop-all-btn').addEventListener('click', stopAll);
$('#clear-btn').addEventListener('click', clearStopped);
$('#autoscroll-btn').addEventListener('click', ()=>{
  autoscroll = !autoscroll;
  $('#autoscroll-btn').textContent = 'Auto-scroll: ' + (autoscroll?'ON':'OFF');
});
$('#clear-log-btn').addEventListener('click', ()=>{ $('#console').innerHTML=''; });
$('#filter-clear').addEventListener('click', (e)=>{ e.preventDefault(); filterBotId=null; updateFilterUI(); renderBots(botsCache); });

// periodic refresh
fetchState();
setInterval(fetchState, 1500);
connectLogs();
</script>
</body>
</html>
'''


# ---------------------------------------------------------------------------
# Startup
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("  MC Bot Summoner  -  offline-mode fake Minecraft players")
    print("  Inspired by mindcraft (github.com/mindcraft-bots/mindcraft)")
    print("=" * 60)
    ensure_environment()

    threading.Thread(target=spawn_worker, daemon=True).start()

    # graceful shutdown of all bots on exit
    def shutdown(*_):
        print("\n[shutdown] stopping all bots ...")
        with bots_lock:
            ids = list(bots.keys())
        for bid in ids:
            stop_bot(bid)
        time.sleep(0.5)
        os._exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    print("[server] starting Flask on http://0.0.0.0:%d ..." % PORT)
    # threaded=True so SSE + API can be served concurrently
    app.run(host="0.0.0.0", port=PORT, threaded=True, use_reloader=False)


if __name__ == "__main__":
    main()
